### ISSUE TITLE
Has it been tested? 

### ISSUE THREAD

**Issue by kishykumar** [dagostini/DAMapAnnotation#1]
Hi, 
I was glad to find out a way to have multiple info windows on iOS Google Maps. 
But, when I downloaded and ran your code, it only shows one info window at a time. 

I was wondering if you tested your code because it's not working for me?

**Comment by dagostini** [comment]
Hi,
It was tested, it works, the problem was there was no autolayout (don't know why), so the toggle button was not visible. I commited the fix, so it should be fine for you now.

If you're going to use this in your app just be aware that if you have too many markers visible on the map you'll have memory issues because the markers are rendered as images. We found that having 100 markers is optimal.

Let me know if you have any more problems, and have a nice day :)
Dejan.

**Comment by kishykumar** [comment]
Thanks Dejan. 
I'll try it out soon. This seems very helpful. 

Also, I am going to use just 2 markers. So, I am good. :)

**Comment by dagostini** [comment]
No worries, glad I could help a fellow developer :)

**Comment by kishykumar** [comment]
There are a few questions on StackOverflow on how to achieve this. I'll publicize your repo over there. :)

**Comment by dagostini** [comment]
Sure, go right ahead :)
